import warnings
import sys
import unittest

from src.HerNeuralMCTS.src.main import run

warnings.filterwarnings("ignore")


class TestA0(unittest.TestCase):

    def test_a0_bitflip(self):
        sys.argv += (
            " --experiment_name her8_b50"
            " --num_iterations 50"
            " --seed 1"
            " --wandb online"
            " --logging_level 10"
            " --num_selfplay_episodes 50"
            " --num_selfplay_episodes_test 20"
            " --test_frequency 3"
            " --minimum_reward -1"
            " --maximum_reward 0"
            " --batch_size_training 256"
            " --num_gradient_steps 30"
            " --cold_start_iterations 1"
            " --num_mcts_sims 50"
            " --c1 1"
            " --gamma 0.98"
            " --risk_seeking True"
            " --selfplay_buffer_window 10"
            " --hindsight_samples 8"
            " --hindsight_policy original"
            " --hindsight_goal_selection future"
            " --hindsight_trajectory_selection played"
            " --hindsight_num_trajectories 1"
            " --hindsight_aggressive_returns_lambda 1"
            " --hindsight_experience_ranking False"
            " --hindsight_experience_ranking_threshold 0.5"
            " --hindsight_combined_experience_replay False"
            " --game gym"
            " --gym_env_str BitFlip"
            " --gym_max_episode_steps 50"
            " --gym_lr 0.0005"
            " --gym_test_generalization off"
            " --project_name her-neural-mcts-bitflip"
        ).split()
        run()

    def test_a0_mmaze(self):
        sys.argv += (
            " --experiment_name her8_mmaze"
            " --num_iterations 50"
            " --seed 1"
            " --wandb online"
            " --logging_level 10"
            " --num_selfplay_episodes 20"
            " --num_selfplay_episodes_test 10"
            " --test_frequency 3"
            " --minimum_reward -1"
            " --maximum_reward 0"
            " --batch_size_training 256"
            " --num_gradient_steps 10"
            " --cold_start_iterations 1"
            " --num_mcts_sims 20"
            " --c1 1"
            " --gamma 0.99"
            " --risk_seeking True"
            " --selfplay_buffer_window 10"
            " --hindsight_samples 8"
            " --hindsight_policy original"
            " --hindsight_goal_selection future"
            " --hindsight_trajectory_selection played"
            " --hindsight_aggressive_returns_lambda 1"
            " --hindsight_experience_ranking False"
            " --hindsight_experience_ranking_threshold 0.5"
            " --hindsight_num_trajectories 1"
            " --hindsight_combined_experience_replay False"
            " --game gym"
            " --gym_env_str PointMaze_Medium-v3"
            " --gym_max_episode_steps 500"
            " --gym_lr 0.00025"
            " --gym_test_generalization off"
            " --project_name her-neural-mcts-mmaze"
        ).split()
        run()

    def test_a0_equation_discovery(self):
        sys.argv += (
            " --experiment_name her100_equation"
            " --num_iterations 100"
            " --max_num_nodes_in_syntax_tree 25"
            " --seed 1"
            " --wandb disabled"
            " --logging_level 20"
            " --num_selfplay_episodes 50"
            " --num_selfplay_episodes_test 50"
            " --test_frequency 3"
            " --minimum_reward -1"
            " --maximum_reward 1"
            " --max_depth_of_tree 10"
            " --max_branching_factor 2"
            " --max_constants_in_tree 5"
            " --batch_size_training 64"
            " --num_gradient_steps 20"
            " --cold_start_iterations 1"
            " --equation_preprocess_class GenPandasPreprocess"
            " --num_rows_for_ed 100"
            " --class_equation_encoder Transformer_Encoder_String"
            " --embedding_dim_encoder_equation 8"
            " --max_tokens_equation 64"
            " --use_position_encoding False"
            " --num_layer_encoder_equation_transformer 2"
            " --num_heads_encoder_equation_transformer 4"
            " --dim_feed_forward_equation_encoder_transformer 32"
            " --dropout_rate 0.1"
            " --class_measurement_encoder LSTM_Measurement_Encoder"
            " --normalize_approach abs_max_y"
            " --contrastive_loss False"
            " --encoder_measurements_LSTM_units 64"
            " --encoder_measurements_LSTM_return_sequence True"
            " --encoder_measurement_num_layer 3"
            " --encoder_measurement_num_neurons 128"
            " --model_dim_hidden_dataset_transformer 128"
            " --model_num_heads_dataset_transformer 8"
            " --model_stacking_depth_dataset_transformer 4"
            " --model_sep_res_embed_dataset_transformer True"
            " --model_att_block_layer_norm_dataset_transformer True"
            " --model_layer_norm_eps_dataset_transformer 1e-12"
            " --model_att_score_norm_dataset_transformer softmax"
            " --model_pre_layer_norm_dataset_transformer False"
            " --model_rff_depth_dataset_transformer 2"
            " --model_hidden_dropout_prob_dataset_transformer 1e-06"
            " --model_att_score_dropout_prob_dataset_transformer 1e-06"
            " --model_mix_heads_dataset_transformer True"
            " --model_embedding_layer_norm_dataset_transformer False"
            " --bit_embedding_dataset_transformer False"
            " --dataset_transformer_use_latent_vector True"
            " --use_feature_index_embedding_dataset_transformer False"
            " --float_precision_text_transformer 3"
            " --mantissa_len_text_transformer 1"
            " --max_exponent_text_transformer 100"
            " --num_dimensions_text_transformer 3"
            " --embedding_dim_text_transformer 512"
            " --embedder_intermediate_expansion_factor_text_transformer 1.0"
            " --num_encoder_layers_text_transformer 4"
            " --num_attention_heads_text_transformer 8"
            " --encoder_intermediate_expansion_factor_text_transformer 4.0"
            " --intermediate_dropout_rate_text_transformer 0.2"
            " --attention_dropout_rate_text_transformer 0.1"
            " --actor_decoder_class mlp_decoder"
            " --actor_decoder_normalize_way soft_max"
            " --critic_decoder_class mlp_decoder"
            " --critic_decoder_normalize_way tanh"
            " --num_mcts_sims 100"
            " --mcts_engine Endgame"
            " --c1 1.41421356237"
            " --gamma 1"
            " --depth_first_search False"
            " --selfplay_buffer_window 50"
            " --data data/gen"
            " --grammar_search curated_equations"
            " --training_mode mcts"
            " --supervised_gen_df True"
            " --training_after episode"
            " --hindsight_samples 1"
            " --hindsight_gen_df True"
            " --hindsight_policy one_hot"
            " --hindsight_goal_selection final"
            " --hindsight_trajectory_selection mcts_random"
            " --hindsight_num_trajectories 100"
            " --hindsight_aggressive_returns_lambda 1"
            " --hindsight_experience_ranking False"
            " --hindsight_experience_ranking_threshold 0.5"
            " --hindsight_combined_experience_replay False"
            " --game equation"
            " --project_name her-neural-mcts-equation"
        ).split()
        run()
